- hosts: terraform-ansible
  tasks:
    - name: instalando o python 3, e virtual env
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependênciasc om pip
      pip: 
        virtualenv: /home/ubuntu/testes/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando o projeto
      shell: '. /home/ubuntu/testes/venv/bin/activate; django-admin startproject setup /home/ubuntu/testes/'
    - name: Alterando o hosts do settings
      lineinfile:
        path: /home/ubuntu/testes/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
